from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from .identifiers import lua_quote
from .models import CraftItemDef, NodeDef, OpenRealmPlan, Placement, Recipe, Structure, ToolDef
from .png_tools import write_solid_png
from .safety import validate_plan

PALETTE = [
    (122, 92, 255),
    (78, 168, 255),
    (46, 212, 183),
    (139, 227, 107),
    (246, 247, 250),
    (40, 48, 70),
]


def generate_luanti_mod(plan: OpenRealmPlan, out_dir: Path) -> Path:
    """Generate an installable Luanti mod from a validated OpenRealm plan."""
    report = validate_plan(plan)
    report.raise_for_errors()

    mod_dir = out_dir / plan.mod_name
    textures_dir = mod_dir / "textures"
    mod_dir.mkdir(parents=True, exist_ok=True)
    textures_dir.mkdir(parents=True, exist_ok=True)

    _write_mod_conf(plan, mod_dir / "mod.conf")
    _write_plan_json(plan, mod_dir / "openrealm_plan.json")
    _write_readme(plan, mod_dir / "README.md")
    _write_textures(plan, textures_dir)
    (mod_dir / "init.lua").write_text(_lua_for_plan(plan), encoding="utf-8")
    return mod_dir


def _write_mod_conf(plan: OpenRealmPlan, path: Path) -> None:
    path.write_text(
        f"name = {plan.mod_name}\n"
        f"title = {plan.title}\n"
        f"description = Generated by OpenRealm Creator Kernel. Preview/approval/rollback oriented.\n"
        f"depends = default\n"
        f"optional_depends = fire,tnt,stairs,doors,wool,farming\n",
        encoding="utf-8",
    )


def _write_plan_json(plan: OpenRealmPlan, path: Path) -> None:
    path.write_text(plan.to_json() + "\n", encoding="utf-8")


def _write_readme(plan: OpenRealmPlan, path: Path) -> None:
    commands = ["/or_preview"]
    if plan.structures:
        commands.append("/or_build <structure_name>")
        commands.append("/or_rollback_last")
    path.write_text(
        "# " + plan.title + "\n\n"
        + plan.summary + "\n\n"
        + "Generated by OpenRealm Creator Kernel. Install in a disposable test world first.\n\n"
        + "## Commands\n\n"
        + "\n".join(f"- `{cmd}`" for cmd in commands)
        + "\n\n## Safety\n\n"
        + "- AI did not directly mutate the world.\n"
        + "- Changes are template-generated from a data-only plan.\n"
        + "- Structures are bounded and protected-area aware.\n"
        + "- Rollback metadata is stored before structure placement.\n",
        encoding="utf-8",
    )


def _texture_name(plan: OpenRealmPlan, local_name: str) -> str:
    return f"{plan.mod_name}_{local_name}.png"


def _write_textures(plan: OpenRealmPlan, textures_dir: Path) -> None:
    entries: list[tuple[str, str]] = []
    entries.extend((node.name, node.texture_hint) for node in plan.nodes)
    entries.extend((item.name, item.inventory_image_hint) for item in plan.craft_items)
    entries.extend((tool.name, tool.inventory_image_hint) for tool in plan.tools)
    for index, (name, hint) in enumerate(entries):
        seed = sum(ord(ch) for ch in name + hint)
        base = PALETTE[seed % len(PALETTE)]
        write_solid_png(textures_dir / _texture_name(plan, name), base, checker=True)


def _lua_table(values: Iterable[str]) -> str:
    return "{ " + ", ".join(values) + " }"


def _lua_groups(groups: dict[str, int]) -> str:
    if not groups:
        return "{}"
    parts = [f"{key} = {int(value)}" for key, value in sorted(groups.items())]
    return "{ " + ", ".join(parts) + " }"


def _register_node(plan: OpenRealmPlan, node: NodeDef) -> str:
    fields = [
        f"description = {lua_quote(node.description)}",
        f"tiles = {{ {lua_quote(_texture_name(plan, node.name))} }}",
        f"groups = {_lua_groups(node.groups)}",
    ]
    if node.light_source:
        fields.append(f"light_source = {int(node.light_source)}")
    if node.drawtype != "normal":
        fields.append(f"drawtype = {lua_quote(node.drawtype)}")
    if node.paramtype:
        fields.append(f"paramtype = {lua_quote(node.paramtype)}")
    if node.walkable is False:
        fields.append("walkable = false")
    body = ",\n\t".join(fields)
    return f"minetest.register_node(MOD .. \":{node.name}\", {{\n\t{body}\n}})"


def _register_craftitem(plan: OpenRealmPlan, item: CraftItemDef) -> str:
    return (
        f"minetest.register_craftitem(MOD .. \":{item.name}\", {{\n"
        f"\tdescription = {lua_quote(item.description)},\n"
        f"\tinventory_image = {lua_quote(_texture_name(plan, item.name))}\n"
        f"}})"
    )


def _register_tool(plan: OpenRealmPlan, tool: ToolDef) -> str:
    groups = _lua_groups(tool.damage_groups)
    return (
        f"minetest.register_tool(MOD .. \":{tool.name}\", {{\n"
        f"\tdescription = {lua_quote(tool.description)},\n"
        f"\tinventory_image = {lua_quote(_texture_name(plan, tool.name))},\n"
        f"\ttool_capabilities = {{\n"
        f"\t\tfull_punch_interval = {tool.full_punch_interval},\n"
        f"\t\tdamage_groups = {groups}\n"
        f"\t}}\n"
        f"}})"
    )


def _register_recipe(recipe: Recipe) -> str:
    rows = []
    for row in recipe.recipe:
        rows.append(_lua_table(lua_quote(cell) for cell in row))
    return (
        "minetest.register_craft({\n"
        f"\toutput = {lua_quote(recipe.output)},\n"
        f"\trecipe = {{\n\t\t" + ",\n\t\t".join(rows) + "\n\t}\n"
        "})"
    )


def _register_ore(ore) -> str:
    return (
        "minetest.register_ore({\n"
        "\tore_type = \"scatter\",\n"
        f"\tore = {lua_quote(ore.ore)},\n"
        f"\twherein = {lua_quote(ore.wherein)},\n"
        f"\tclust_scarcity = {int(ore.clust_scarcity)},\n"
        f"\tclust_num_ores = {int(ore.clust_num_ores)},\n"
        f"\tclust_size = {int(ore.clust_size)},\n"
        f"\ty_min = {int(ore.y_min)},\n"
        f"\ty_max = {int(ore.y_max)}\n"
        "})"
    )


def _lua_placement(p: Placement) -> str:
    return f"{{ x = {p.x}, y = {p.y}, z = {p.z}, node = {lua_quote(p.node)} }}"


def _lua_structures(structures: list[Structure]) -> str:
    if not structures:
        return "local STRUCTURES = {}"
    chunks = ["local STRUCTURES = {"]
    for s in structures:
        placements = ",\n\t\t\t".join(_lua_placement(p) for p in s.placements)
        chunks.append(
            f"\t{s.name} = {{\n"
            f"\t\tdescription = {lua_quote(s.description)},\n"
            f"\t\tplacements = {{\n\t\t\t{placements}\n\t\t}}\n"
            f"\t}},"
        )
    chunks.append("}")
    return "\n".join(chunks)


def _lua_for_plan(plan: OpenRealmPlan) -> str:
    sections = []
    sections.append("-- Generated by OpenRealm Creator Kernel. Do not edit by hand unless you know what you are doing.")
    sections.append("local MOD = minetest.get_current_modname()")
    sections.append("local storage = minetest.get_mod_storage()")
    sections.append(f"local PLAN_ID = {lua_quote(plan.plan_id)}")
    sections.append(f"local PLAN_TITLE = {lua_quote(plan.title)}")
    sections.append(f"local PLAN_SUMMARY = {lua_quote(plan.summary)}")
    sections.append("")
    for node in plan.nodes:
        sections.append(_register_node(plan, node))
    for item in plan.craft_items:
        sections.append(_register_craftitem(plan, item))
    for tool in plan.tools:
        sections.append(_register_tool(plan, tool))
    for recipe in plan.recipes:
        sections.append(_register_recipe(recipe))
    for ore in plan.ores:
        sections.append(_register_ore(ore))
    sections.append(_lua_structures(plan.structures))
    sections.append(_runtime_lua(plan))
    return "\n\n".join(sections) + "\n"


def _runtime_lua(plan: OpenRealmPlan) -> str:
    structures_list = ", ".join(s.name for s in plan.structures) or "none"
    max_nodes = plan.safety_budget.max_structure_nodes
    return f"""
local function chat(name, message)
    minetest.chat_send_player(name, "[OpenRealm] " .. message)
end

local function structure_names()
    local names = {{}}
    for name, _ in pairs(STRUCTURES) do
        table.insert(names, name)
    end
    table.sort(names)
    return table.concat(names, ", ")
end

minetest.register_chatcommand("or_preview", {{
    params = "",
    description = "Preview this OpenRealm generated plan.",
    func = function(name)
        chat(name, PLAN_TITLE .. " - " .. PLAN_SUMMARY)
        chat(name, "Plan id: " .. PLAN_ID)
        chat(name, "Structures: " .. structure_names())
        chat(name, "Safety: preview required, approval required, rollback metadata enabled.")
        return true
    end,
}})

local function player_base(name)
    local player = minetest.get_player_by_name(name)
    if not player then
        return nil
    end
    local pos = player:get_pos()
    return vector.round(vector.add(pos, {{ x = 2, y = 0, z = 2 }}))
end

local function node_count(structure)
    return #(structure.placements or {{}})
end

local function rollback_key(name)
    return "rollback:" .. name
end

local function store_rollback(name, records)
    storage:set_string(rollback_key(name), minetest.write_json(records))
end

local function load_rollback(name)
    local raw = storage:get_string(rollback_key(name))
    if raw == nil or raw == "" then
        return nil
    end
    return minetest.parse_json(raw)
end

local function clear_rollback(name)
    storage:set_string(rollback_key(name), "")
end

local function build_structure(name, structure_name)
    local structure = STRUCTURES[structure_name]
    if not structure then
        return false, "Unknown structure. Available: " .. structure_names()
    end
    if node_count(structure) > {max_nodes} then
        return false, "Structure exceeds OpenRealm node budget."
    end
    local base = player_base(name)
    if not base then
        return false, "Player is not available."
    end
    local rollback = {{}}
    for _, p in ipairs(structure.placements) do
        local pos = vector.add(base, {{ x = p.x, y = p.y, z = p.z }})
        if minetest.is_protected(pos, name) then
            return false, "Protected area blocked build at " .. minetest.pos_to_string(pos)
        end
        local old = minetest.get_node_or_nil(pos)
        rollback[#rollback + 1] = {{ pos = pos, old = old or {{ name = "air" }} }}
    end
    store_rollback(name, rollback)
    for _, p in ipairs(structure.placements) do
        local pos = vector.add(base, {{ x = p.x, y = p.y, z = p.z }})
        minetest.set_node(pos, {{ name = p.node }})
    end
    minetest.log("action", "[OpenRealm] " .. name .. " built " .. structure_name .. " plan=" .. PLAN_ID .. " nodes=" .. node_count(structure))
    return true, "Built " .. structure_name .. " with " .. node_count(structure) .. " nodes. Rollback available with /or_rollback_last."
end

minetest.register_chatcommand("or_build", {{
    params = "<structure_name>",
    description = "Build a generated OpenRealm structure after previewing it.",
    privs = {{ interact = true }},
    func = function(name, param)
        local structure_name = (param or ""):gsub("^%s+", ""):gsub("%s+$", "")
        if structure_name == "" then
            return false, "Usage: /or_build <structure_name>. Available: " .. structure_names()
        end
        local ok, message = build_structure(name, structure_name)
        return ok, "[OpenRealm] " .. message
    end,
}})

minetest.register_chatcommand("or_rollback_last", {{
    params = "",
    description = "Rollback your last OpenRealm generated build from this mod.",
    privs = {{ interact = true }},
    func = function(name)
        local records = load_rollback(name)
        if not records or #records == 0 then
            return false, "[OpenRealm] No rollback record found."
        end
        for i = #records, 1, -1 do
            local record = records[i]
            if record.pos and record.old and not minetest.is_protected(record.pos, name) then
                minetest.set_node(record.pos, record.old)
            end
        end
        clear_rollback(name)
        minetest.log("action", "[OpenRealm] " .. name .. " rolled back plan=" .. PLAN_ID .. " nodes=" .. #records)
        return true, "[OpenRealm] Rolled back " .. #records .. " nodes."
    end,
}})

minetest.log("action", "[OpenRealm] Loaded generated plan " .. PLAN_ID .. " structures={structures_list}")
""".strip()
