from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from .identifiers import lua_quote
from .models import CraftItemDef, NodeDef, OpenRealmPlan, Placement, Recipe, Structure, ToolDef
from .png_tools import write_solid_png
from .safety import validate_plan

PALETTE = [
    (122, 92, 255),
    (78, 168, 255),
    (46, 212, 183),
    (139, 227, 107),
    (246, 247, 250),
    (40, 48, 70),
]


def generate_luanti_mod(plan: OpenRealmPlan, out_dir: Path) -> Path:
    """Generate an installable Luanti mod from a validated OpenRealm plan."""
    report = validate_plan(plan)
    report.raise_for_errors()

    mod_dir = out_dir / plan.mod_name
    textures_dir = mod_dir / "textures"
    mod_dir.mkdir(parents=True, exist_ok=True)
    textures_dir.mkdir(parents=True, exist_ok=True)

    _write_mod_conf(plan, mod_dir / "mod.conf")
    _write_plan_json(plan, mod_dir / "openrealm_plan.json")
    _write_readme(plan, mod_dir / "README.md")
    _write_textures(plan, textures_dir)
    (mod_dir / "init.lua").write_text(_lua_for_plan(plan), encoding="utf-8")
    return mod_dir


def _write_mod_conf(plan: OpenRealmPlan, path: Path) -> None:
    path.write_text(
        f"name = {plan.mod_name}\n"
        f"title = {plan.title}\n"
        f"description = Generated by OpenRealm Creator Kernel. Preview/approval/rollback oriented.\n"
        f"depends = default\n"
        f"optional_depends = fire,tnt,stairs,doors,wool,farming,ai_runtime_base\n",
        encoding="utf-8",
    )


def _write_plan_json(plan: OpenRealmPlan, path: Path) -> None:
    path.write_text(plan.to_json() + "\n", encoding="utf-8")


def _write_readme(plan: OpenRealmPlan, path: Path) -> None:
    commands = ["/or_preview"]
    if plan.structures:
        commands.append("/or_build <structure_name>")
        commands.append("/or_rollback_last")
    path.write_text(
        "# " + plan.title + "\n\n"
        + plan.summary + "\n\n"
        + "Generated by OpenRealm Creator Kernel. Install in a disposable test world first.\n\n"
        + "## Commands\n\n"
        + "\n".join(f"- `{cmd}`" for cmd in commands)
        + "\n\n## Safety\n\n"
        + "- AI did not directly mutate the world.\n"
        + "- Changes are template-generated from a data-only plan.\n"
        + "- Structures are queued through the AI runtime import task queue when available.\n"
        + "- Rollback metadata is stored by the AI runtime before structure placement.\n",
        encoding="utf-8",
    )


def _texture_name(plan: OpenRealmPlan, local_name: str) -> str:
    return f"{plan.mod_name}_{local_name}.png"


def _write_textures(plan: OpenRealmPlan, textures_dir: Path) -> None:
    entries: list[tuple[str, str]] = []
    entries.extend((node.name, node.texture_hint) for node in plan.nodes)
    entries.extend((item.name, item.inventory_image_hint) for item in plan.craft_items)
    entries.extend((tool.name, tool.inventory_image_hint) for tool in plan.tools)
    for index, (name, hint) in enumerate(entries):
        seed = sum(ord(ch) for ch in name + hint)
        base = PALETTE[seed % len(PALETTE)]
        write_solid_png(textures_dir / _texture_name(plan, name), base, checker=True)


def _lua_table(values: Iterable[str]) -> str:
    return "{ " + ", ".join(values) + " }"


def _lua_groups(groups: dict[str, int]) -> str:
    if not groups:
        return "{}"
    parts = [f"{key} = {int(value)}" for key, value in sorted(groups.items())]
    return "{ " + ", ".join(parts) + " }"


def _register_node(plan: OpenRealmPlan, node: NodeDef) -> str:
    fields = [
        f"description = {lua_quote(node.description)}",
        f"tiles = {{ {lua_quote(_texture_name(plan, node.name))} }}",
        f"groups = {_lua_groups(node.groups)}",
    ]
    if node.light_source:
        fields.append(f"light_source = {int(node.light_source)}")
    if node.drawtype != "normal":
        fields.append(f"drawtype = {lua_quote(node.drawtype)}")
    if node.paramtype:
        fields.append(f"paramtype = {lua_quote(node.paramtype)}")
    if node.walkable is False:
        fields.append("walkable = false")
    body = ",\n\t".join(fields)
    return f"minetest.register_node(MOD .. \":{node.name}\", {{\n\t{body}\n}})"


def _register_craftitem(plan: OpenRealmPlan, item: CraftItemDef) -> str:
    return (
        f"minetest.register_craftitem(MOD .. \":{item.name}\", {{\n"
        f"\tdescription = {lua_quote(item.description)},\n"
        f"\tinventory_image = {lua_quote(_texture_name(plan, item.name))}\n"
        f"}})"
    )


def _register_tool(plan: OpenRealmPlan, tool: ToolDef) -> str:
    groups = _lua_groups(tool.damage_groups)
    return (
        f"minetest.register_tool(MOD .. \":{tool.name}\", {{\n"
        f"\tdescription = {lua_quote(tool.description)},\n"
        f"\tinventory_image = {lua_quote(_texture_name(plan, tool.name))},\n"
        f"\ttool_capabilities = {{\n"
        f"\t\tfull_punch_interval = {tool.full_punch_interval},\n"
        f"\t\tdamage_groups = {groups}\n"
        f"\t}}\n"
        f"}})"
    )


def _register_recipe(recipe: Recipe) -> str:
    rows = []
    for row in recipe.recipe:
        rows.append(_lua_table(lua_quote(cell) for cell in row))
    return (
        "minetest.register_craft({\n"
        f"\toutput = {lua_quote(recipe.output)},\n"
        f"\trecipe = {{\n\t\t" + ",\n\t\t".join(rows) + "\n\t}\n"
        "})"
    )


def _register_ore(ore) -> str:
    return (
        "minetest.register_ore({\n"
        "\tore_type = \"scatter\",\n"
        f"\tore = {lua_quote(ore.ore)},\n"
        f"\twherein = {lua_quote(ore.wherein)},\n"
        f"\tclust_scarcity = {int(ore.clust_scarcity)},\n"
        f"\tclust_num_ores = {int(ore.clust_num_ores)},\n"
        f"\tclust_size = {int(ore.clust_size)},\n"
        f"\ty_min = {int(ore.y_min)},\n"
        f"\ty_max = {int(ore.y_max)}\n"
        "})"
    )


def _lua_placement(p: Placement) -> str:
    return f"{{ x = {p.x}, y = {p.y}, z = {p.z}, node = {lua_quote(p.node)} }}"


def _lua_structures(structures: list[Structure]) -> str:
    if not structures:
        return "local STRUCTURES = {}"
    chunks = ["local STRUCTURES = {"]
    for s in structures:
        placements = ",\n\t\t\t".join(_lua_placement(p) for p in s.placements)
        chunks.append(
            f"\t{s.name} = {{\n"
            f"\t\tdescription = {lua_quote(s.description)},\n"
            f"\t\tplacements = {{\n\t\t\t{placements}\n\t\t}}\n"
            f"\t}},"
        )
    chunks.append("}")
    return "\n".join(chunks)


def _lua_for_plan(plan: OpenRealmPlan) -> str:
    sections = []
    sections.append("-- Generated by OpenRealm Creator Kernel. Do not edit by hand unless you know what you are doing.")
    sections.append("local MOD = minetest.get_current_modname()")
    sections.append(f"local PLAN_ID = {lua_quote(plan.plan_id)}")
    sections.append(f"local PLAN_TITLE = {lua_quote(plan.title)}")
    sections.append(f"local PLAN_SUMMARY = {lua_quote(plan.summary)}")
    sections.append("")
    for node in plan.nodes:
        sections.append(_register_node(plan, node))
    for item in plan.craft_items:
        sections.append(_register_craftitem(plan, item))
    for tool in plan.tools:
        sections.append(_register_tool(plan, tool))
    for recipe in plan.recipes:
        sections.append(_register_recipe(recipe))
    for ore in plan.ores:
        sections.append(_register_ore(ore))
    sections.append(_lua_structures(plan.structures))
    sections.append(_runtime_lua(plan))
    return "\n\n".join(sections) + "\n"


def _runtime_lua(plan: OpenRealmPlan) -> str:
    structures_list = ", ".join(s.name for s in plan.structures) or "none"
    max_nodes = plan.safety_budget.max_structure_nodes
    return f"""
local function chat(name, message)
    minetest.chat_send_player(name, "[OpenRealm] " .. message)
end

local function structure_names()
    local names = {{}}
    for name, _ in pairs(STRUCTURES) do
        table.insert(names, name)
    end
    table.sort(names)
    return table.concat(names, ", ")
end

minetest.register_chatcommand("or_preview", {{
    params = "",
    description = "Preview this OpenRealm generated plan.",
    func = function(name)
        chat(name, PLAN_TITLE .. " - " .. PLAN_SUMMARY)
        chat(name, "Plan id: " .. PLAN_ID)
        chat(name, "Structures: " .. structure_names())
        chat(name, "Safety: preview required, approval required, AI runtime queue required, rollback metadata enabled.")
        return true
    end,
}})

local function player_base(name)
    local player = minetest.get_player_by_name(name)
    if not player then
        return nil
    end
    local pos = player:get_pos()
    return vector.round(vector.add(pos, {{ x = 2, y = 0, z = 2 }}))
end

local function node_count(structure)
    return #(structure.placements or {{}})
end

local OPENREALM_AGENT_ID = MOD .. ":generated_builder"
local task_counter = 0

local function runtime_core()
    local candidate = rawget(_G, "core") or minetest
    if type(candidate) ~= "table" then
        return nil
    end
    if type(candidate.ai_import_ops) ~= "table" then
        return nil
    end
    if type(candidate.ai_import_ops.queue_chunked_structure_apply_task) ~= "function" then
        return nil
    end
    if type(candidate.register_ai_agent) ~= "function" then
        return nil
    end
    return candidate
end

local function id_part(value)
    return tostring(value):gsub("[^%w._:-]", "_")
end

local function next_task_nonce()
    task_counter = task_counter + 1
    if minetest.get_us_time then
        return tostring(minetest.get_us_time()) .. ":" .. tostring(task_counter)
    end
    return tostring(task_counter)
end

local function runtime_world_id()
    if minetest.settings and minetest.settings:get("openrealm.world_id") then
        local configured = minetest.settings:get("openrealm.world_id")
        if configured and configured ~= "" then
            return configured
        end
    end
    return "openrealm-disposable-world"
end

local function ensure_runtime_agent(api)
    if type(api.get_ai_agent) == "function" and api.get_ai_agent(OPENREALM_AGENT_ID) then
        return true
    end
    local ok, err = pcall(api.register_ai_agent, {{
        agent_id = OPENREALM_AGENT_ID,
        display_name = "OpenRealm Generated Builder",
        owner = "openrealm",
        plugin = MOD,
        capabilities = {{
            ["import.assets"] = true,
            ["world.place"] = true,
            ["world.batch"] = true,
        }},
        limits = {{
            max_structure_nodes = {max_nodes},
        }},
    }})
    if not ok then
        return false, tostring(err)
    end
    return true
end

local function runtime_placements(name, base, structure)
    local placements = {{}}
    for _, p in ipairs(structure.placements) do
        local pos = vector.add(base, {{ x = p.x, y = p.y, z = p.z }})
        if minetest.is_protected(pos, name) then
            return nil, "Protected area blocked build at " .. minetest.pos_to_string(pos)
        end
        placements[#placements + 1] = {{
            pos = pos,
            node_name = p.node,
        }}
    end
    return placements
end

local function chunk_size_for(count)
    local size = math.min(32, count)
    if size < 1 then
        return 1
    end
    return size
end

local function queue_structure_build(name, structure_name, structure)
    local api = runtime_core()
    if not api then
        return false, "OpenRealm AI runtime import queue is not available. Run this mod in the ai_runtime profile before building."
    end
    local agent_ok, agent_err = ensure_runtime_agent(api)
    if not agent_ok then
        return false, "OpenRealm runtime agent registration failed: " .. tostring(agent_err)
    end
    local base = player_base(name)
    if not base then
        return false, "Player is not available."
    end
    local placements, placement_err = runtime_placements(name, base, structure)
    if not placements then
        return false, placement_err
    end

    local world_id = runtime_world_id()
    local task_id = "openrealm:" .. id_part(PLAN_ID) .. ":" .. id_part(structure_name)
        .. ":" .. id_part(name) .. ":" .. id_part(next_task_nonce())
    local step_size = chunk_size_for(#placements)
    local ok, queued = pcall(api.ai_import_ops.queue_chunked_structure_apply_task, {{
        task_id = task_id,
        agent_id = OPENREALM_AGENT_ID,
        owner = name,
        label = "openrealm.structure.place",
        report_id = PLAN_ID,
        action_index = 0,
        world_id = world_id,
        target_world = {{
            world_id = world_id,
            staging = true,
            disposable = true,
        }},
        staging = true,
        explicit_approval = true,
        allow_mutation = true,
        rollback_policy = "chunked",
        mutation_class = "compat_import",
        operation_label = "openrealm.structure.apply",
        placements = placements,
        chunk_size = step_size,
        max_node_writes_per_step = step_size,
        max_node_writes_total = {max_nodes},
        max_mapblock_churn_total = {max_nodes},
        source_reference = {{
            reference_type = "openrealm_plan",
            redacted_id = PLAN_ID .. ":" .. structure_name,
            inventory_hash = PLAN_ID,
        }},
    }})
    if not ok then
        return false, "Failed to queue AI runtime task: " .. tostring(queued)
    end
    if type(api.record_ai_runtime_audit) == "function" then
        api.record_ai_runtime_audit({{
            event_type = "openrealm.structure_queued",
            agent_id = OPENREALM_AGENT_ID,
            task_id = task_id,
            actor = name,
            operation = "openrealm.structure.queue",
            status = "queued",
            reason = "runtime_task_queued",
            message = "OpenRealm structure queued through AI runtime.",
        }})
    end
    minetest.log("action", "[OpenRealm] " .. name .. " queued " .. structure_name
        .. " plan=" .. PLAN_ID .. " task=" .. task_id .. " nodes=" .. node_count(structure))
    return true, "Queued " .. structure_name .. " as AI runtime task " .. task_id
        .. " with " .. node_count(structure) .. " planned nodes. Track it with /ai_runtime_operator_status view=task task_id=" .. task_id
end

local function build_structure(name, structure_name)
    local structure = STRUCTURES[structure_name]
    if not structure then
        return false, "Unknown structure. Available: " .. structure_names()
    end
    if node_count(structure) > {max_nodes} then
        return false, "Structure exceeds OpenRealm node budget."
    end
    return queue_structure_build(name, structure_name, structure)
end

minetest.register_chatcommand("or_build", {{
    params = "<structure_name>",
    description = "Queue a generated OpenRealm structure through the AI runtime after previewing it.",
    privs = {{ interact = true }},
    func = function(name, param)
        local structure_name = (param or ""):gsub("^%s+", ""):gsub("%s+$", "")
        if structure_name == "" then
            return false, "Usage: /or_build <structure_name>. Available: " .. structure_names()
        end
        local ok, message = build_structure(name, structure_name)
        return ok, "[OpenRealm] " .. message
    end,
}})

minetest.register_chatcommand("or_rollback_last", {{
    params = "",
    description = "Show how to inspect AI runtime rollback records for OpenRealm generated builds.",
    privs = {{ interact = true }},
    func = function(_name)
        return false, "[OpenRealm] Rollback is managed by AI runtime rollback records. Use /ai_runtime_operator_status view=rollback, then use the operator rollback flow."
    end,
}})

minetest.log("action", "[OpenRealm] Loaded generated plan " .. PLAN_ID .. " structures={structures_list}")
""".strip()
